- name: squid 
  hosts: Server
  user: root 
  tasks:
  -  name: configurac√≠on squid
     ansible.builtin.copy: 
       remote_src: /home/usuario/ansibles/docs/configuracion_squid
       dest: /etc/squid/squid.conf 
  - name: Reiniciar squid 
    ansible.builtin.systemd:
      name: squid 
      state: restarted 